/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import BUS.MenuBUS;
import DAO.MenuDAO;
import DTO.ChucNang;
import DTO.NhanVien;
import SWING.MenuItem;
import cua_hang_quan_ao.Cua_hang_quan_ao;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseListener;
import java.util.ArrayList;

import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.border.EmptyBorder;

import org.w3c.dom.events.MouseEvent;

import cua_hang_quan_ao.*;

/**
 *
 * @author BomPC
 */
public class MenuGUI extends javax.swing.JPanel {

    /**
     * Creates new form MenuGUI
     */
    private MenuBUS menuBUS;
    private Cua_hang_quan_ao app;
    private ArrayList<MenuItem> menuItems;
    private Color bgColor = new Color(76,76,76);

    public MenuGUI(Cua_hang_quan_ao app) {
        this.app = app;
        menuBUS = new MenuBUS(new MenuDAO());
        menuItems = new ArrayList<>();
        initComponents();
        renderInforNV();
        render();
        setupDangXuat();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jlbImage = new javax.swing.JLabel();
        jlbNameNV = new javax.swing.JLabel();
        jlbChucVu = new javax.swing.JLabel();
        jlbDangXuat = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();

        setBackground(new java.awt.Color(51, 51, 51));
        setPreferredSize(new java.awt.Dimension(200, 300));
        setLayout(new java.awt.BorderLayout());

        jPanel1.setPreferredSize(new java.awt.Dimension(614, 260));
        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 0, 0));

        jlbImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-profile-60.png"))); // NOI18N
        jlbImage.setPreferredSize(new java.awt.Dimension(160, 180));
        jPanel1.add(jlbImage);

        jlbNameNV.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jlbNameNV.setForeground(new java.awt.Color(255, 255, 255));
        jlbNameNV.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbNameNV.setPreferredSize(new java.awt.Dimension(200, 22));
        jPanel1.add(jlbNameNV);

        jlbChucVu.setForeground(new java.awt.Color(255, 255, 255));
        jlbChucVu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbChucVu.setPreferredSize(new java.awt.Dimension(200, 22));
        jPanel1.add(jlbChucVu);

        jlbDangXuat.setForeground(new java.awt.Color(255, 255, 255));
        jlbDangXuat.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbDangXuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-sign-out-60.png"))); // NOI18N
        jlbDangXuat.setText("Đăng xuất");
        jlbDangXuat.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(jlbDangXuat);

        add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel3.setPreferredSize(new java.awt.Dimension(200, 200));
        jPanel3.setLayout(new java.awt.BorderLayout());

        jScrollPane1.setBackground(new java.awt.Color(76, 76, 76));
        jScrollPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(76, 76, 76)));
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jPanel2.setPreferredSize(new java.awt.Dimension(100, 2000));
        jPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 0, 0));
        jScrollPane1.setViewportView(jPanel2);

        jPanel3.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        add(jPanel3, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void render() {
        this.setBackground(bgColor);
        jPanel2.setBackground(bgColor);
        jPanel1.setBackground(bgColor);
        jPanel3.setBackground(bgColor);
        Image image1 = ((ImageIcon) jlbDangXuat.getIcon()).getImage();
            Image newimg1 = image1.getScaledInstance(20, 20, java.awt.Image.SCALE_SMOOTH); // scale it the smooth way
            jlbDangXuat.setIcon(new ImageIcon(newimg1));
        ArrayList<ChucNang> dsChucNang = menuBUS
                .getDsChucNang(cua_hang_quan_ao.Cua_hang_quan_ao.nv.getChucVu().getMaNhomQuyen());
        JPanel rootPage = (JPanel) app.getContentPane().getComponent(0);
        rootPage.setBackground(Color.white);
        app.setTitle(dsChucNang.get(0).getTencn());
        choosePage(rootPage, dsChucNang.get(0).getTencn());
        jPanel2.setPreferredSize(new Dimension(200, 50 * dsChucNang.size()));
        jScrollPane1.getVerticalScrollBar().setPreferredSize(new Dimension(5, 0));
        jScrollPane1.getVerticalScrollBar().setUnitIncrement(16);
        for (ChucNang chucNang : dsChucNang) {
            MenuItem menuItem = new MenuItem();
            menuItem.setText(chucNang.getTencn());
            menuItem.setIcon(new ImageIcon(getClass().getResource(chucNang.getIcon())));
            Image image = ((ImageIcon) menuItem.getIcon()).getImage();
            Image newimg = image.getScaledInstance(36, 36, java.awt.Image.SCALE_SMOOTH); // scale it the smooth way
            menuItem.setIcon(new ImageIcon(newimg));
            menuItem.setBorder(new EmptyBorder(0, 15, 0, 0));
            menuItem.setIconTextGap(10);
            menuItem.addMouseListener(new java.awt.event.MouseAdapter() {
                @Override
                public void mousePressed(java.awt.event.MouseEvent e) {
                    app.setTitle(menuItem.getText());
                    rootPage.removeAll();
                    choosePage(rootPage, menuItem.getText());
                    rootPage.repaint();
                    rootPage.revalidate();

                    for (MenuItem item : menuItems) {
                        if (item.isSelected()) {
                            item.setSelected(false);
                            item.setStopedState();
                            break;
                        }
                    }
                    menuItem.setSelected(true);
                }
            });
            jPanel2.add(menuItem);
            menuItems.add(menuItem);
        }
    }

    public void choosePage(JPanel rootPage, String item) {
        ArrayList<String> dsHanhDongCuaChucNang = menuBUS.getDsHanhDong(
            cua_hang_quan_ao.Cua_hang_quan_ao.nv.getChucVu().getMaNhomQuyen(), item);
            
        switch (item) {
            case "Tài khoản":
                rootPage.add(new TaiKhoanGUI(dsHanhDongCuaChucNang));
                break;
            case "Nhân viên":
                rootPage.add(new NhanVienGUI(dsHanhDongCuaChucNang));
                break;
            case "Khách hàng":
                rootPage.add(new KhachHangGUI(dsHanhDongCuaChucNang));
                break;
            case "Sản phẩm":
                rootPage.add(new SanPhamGUI(dsHanhDongCuaChucNang));
                break;
            case "Hóa đơn bán":
                rootPage.add(new HoaDonBanGUI(dsHanhDongCuaChucNang));
                break;
            case "Hóa đơn mua":
                rootPage.add(new HoaDonMuaGUI(dsHanhDongCuaChucNang));
                break;
            case "Nhà cung cấp":
                rootPage.add(new NhaCungCapGUI(dsHanhDongCuaChucNang));
                break;
            case "Khuyến mãi":
                rootPage.add(new KhuyenMaiGUI(dsHanhDongCuaChucNang));
                break;
            case "Nhóm quyền":
                rootPage.add(new NhomQuyenGUI(dsHanhDongCuaChucNang));
                break;
            case "Thống kê":
                rootPage.add(new ThongKeGUI());
                break;
            default:
        }
    }

    public void renderInforNV() {
        // ImageIcon imageIcon = new ImageIcon("./image/logo.png"); // load the image to
        // a imageIcon
        Image image = ((ImageIcon) jlbImage.getIcon()).getImage(); // transform it
        Image newimg = image.getScaledInstance(160, 180, java.awt.Image.SCALE_SMOOTH); // scale it the smooth way
        jlbImage.setIcon(new ImageIcon(newimg));
        jlbImage.setText("");
        jlbImage.setOpaque(true);

        jlbNameNV.setText(Cua_hang_quan_ao.nv.getTenNhanVien());
        jlbChucVu.setText(Cua_hang_quan_ao.nv.getChucVu().getTenNhomQuyen());
    }

    public void setupDangXuat() {
        jlbDangXuat.addMouseListener(new MouseListener() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent e) {
                int option = JOptionPane.showConfirmDialog(
                        null,
                        "Bạn muốn đăng xuất?",
                        "Thông báo",
                        JOptionPane.YES_NO_OPTION,
                        JOptionPane.INFORMATION_MESSAGE);
                if (option == JOptionPane.YES_OPTION) {
                    app.getContentPane().removeAll();
                    app.loginExecute();
                }
            }

            @Override
            public void mouseEntered(java.awt.event.MouseEvent e) {
                jlbDangXuat.setForeground(new Color(26,115,232));

            }

            @Override
            public void mouseExited(java.awt.event.MouseEvent e) {
                jlbDangXuat.setForeground(new Color(255, 255, 255));

            }

            @Override
            public void mousePressed(java.awt.event.MouseEvent e) {
            }

            @Override
            public void mouseReleased(java.awt.event.MouseEvent e) {
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jlbChucVu;
    private javax.swing.JLabel jlbDangXuat;
    private javax.swing.JLabel jlbImage;
    private javax.swing.JLabel jlbNameNV;
    // End of variables declaration//GEN-END:variables
}
