/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import javax.swing.JDialog;
import javax.swing.JOptionPane;

import BUS.HoaDonMuaMoiBUS;
import BUS.NhaCungCapNewShortBUS;
import DAO.NhaCungCapNewShortDAO;
import DTO.NhaCungCap;

/**
 *
 * @author BomPC
 */
public class NhaCungCapNewShortGUI extends javax.swing.JPanel {
    private JDialog dialog;
    private HoaDonMuaMoiBUS hdmmBUS;

    /**
     * Creates new form NhaCungCapNewShortGUI
     */
    public NhaCungCapNewShortGUI(JDialog dialog, HoaDonMuaMoiBUS hdmmBUS) {
        this.dialog = dialog;
        this.hdmmBUS = hdmmBUS;
        initComponents();
        customComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jtfNcc = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jbtnThem = new javax.swing.JButton();
        jbtnHuy = new javax.swing.JButton();

        jPanel3.setPreferredSize(new java.awt.Dimension(352, 40));

        jLabel1.setText("Nhà cung cấp");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 78,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtfNcc, javax.swing.GroupLayout.PREFERRED_SIZE, 168,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(50, 50, 50)));
        jPanel3Layout.setVerticalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jtfNcc, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap()));

        jPanel4.setPreferredSize(new java.awt.Dimension(352, 40));
        java.awt.GridBagLayout jPanel4Layout = new java.awt.GridBagLayout();
        jPanel4Layout.columnWidths = new int[] { 0, 16, 0 };
        jPanel4Layout.rowHeights = new int[] { 0 };
        jPanel4.setLayout(jPanel4Layout);

        jbtnThem.setText("Thêm");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        jPanel4.add(jbtnThem, gridBagConstraints);

        jbtnHuy.setText("Hủy");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        jPanel4.add(jbtnHuy, gridBagConstraints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 34,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 26,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap()));
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JButton jbtnHuy;
    private javax.swing.JButton jbtnThem;
    private javax.swing.JTextField jtfNcc;
    // End of variables declaration//GEN-END:variables

    private NhaCungCapNewShortBUS bus;

    public void customComponents() {
        bus = new NhaCungCapNewShortBUS(new NhaCungCapNewShortDAO());

        jbtnThem.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                String value = jtfNcc.getText().trim();
                if ("".equals(value)) {
                    showAnnouncement("Tên nhà cung cấp là bắt buộc", "Thêm thất bại", JOptionPane.WARNING_MESSAGE);
                    return;
                }
                NhaCungCap ncc = bus.getNccByTen(value);
                if (ncc == null) {
                    int rowEffected = hdmmBUS.addNewShortNcc(value);
                    if (rowEffected > 0) {
                        JOptionPane.showMessageDialog(
                                getParent(),
                                "Nhà cung cấp đã được thêm",
                                "Thêm thành công",
                                JOptionPane.INFORMATION_MESSAGE);
                        jtfNcc.setText("");
                        jtfNcc.requestFocus();
                    }
                } else {
                    JOptionPane.showMessageDialog(
                            getParent(),
                            "Nhà cung cấp đã tồn tại",
                            "Thêm thất bại",
                            JOptionPane.WARNING_MESSAGE);
                }
            }
        });
        jbtnHuy.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                dialog.dispose();
            }
        });

    }

    public void showAnnouncement(String message, String title, int typeMessage) {
        JOptionPane.showMessageDialog(this, message, title, typeMessage);
    }
}
