/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import java.awt.Component;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.time.LocalDate;
import java.time.ZoneId;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.Date;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;

import BUS.NhaCungCapBUS;
import DAO.NhaCungCapDAO;
import DTO.NhaCungCap;
import DTO.NhomQuyen;

/**
 *
 * @author BomPC
 */
public class NhaCungCapGUI extends javax.swing.JPanel {

    /**
     * Creates new form NhaCungCapView
     */
    private NhaCungCapBUS bus;

    public NhaCungCapGUI(ArrayList<String> dsHanhDongCuaChucNang) {
        initComponents();
        bus = new NhaCungCapBUS(new NhaCungCapDAO());
        customComponents();

        jbtnThem.setVisible(false);
		jbtnSua.setVisible(false);
		for (String hd : dsHanhDongCuaChucNang) {
			if (hd.toLowerCase().contains("thêm")) {
				jbtnThem.setVisible(true);
			} else if (hd.toLowerCase().contains("sửa")) {
				jbtnSua.setVisible(true);
			}
		}
    }

    // chuyen cac combobox ,jtextfield tim kiem ve gia tri ban dau
    // public void clearSearchFilter() {
    // jcbNameSearch.setSelectedIndex(0);
    // jtfNameSearch.setText("");
    // jcbStatusSearch.setSelectedIndex(0);
    // }

    // // chuyen sang trang thai mac dinh
    // public void changeToNormalState() {
    // clearThongTinNCCForm();
    // setEnabledThongTinNCCForm(false);
    // jtbDSNCC.setEnabled(true);
    // jbtnXacNhan.setVisible(false);
    // jbtnHuy.setVisible(false);
    // jbtnThem.setEnabled(true);
    // jtbDSNCC.clearSelection();
    // jbtnSua.setEnabled(false);
    // jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Thông tin nhà
    // cung cấp"));
    // }

    // // lam moi cac textfield ,jcombobox trong phan thong tin ncc
    // public void clearThongTinNCCForm() {
    // jtfNcc.setText("");
    // jtfSdt.setText("");
    // jtfDiaChi.setText("");
    // jcbStatus.setSelectedIndex(0);
    // }

    // // enable text field ,jcombobox trong phan thong tin ncc
    // public void setEnabledThongTinNCCForm(boolean condition) {
    // jtfNcc.setEnabled(condition);
    // jtfSdt.setEnabled(condition);
    // jtfDiaChi.setEnabled(condition);
    // jcbStatus.setEnabled(condition);
    // }

    // // load 1 ncc tu 1 dong cua jtable va hien len textfield ,combobox trong phan
    // // thong tin ncc

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jbtnThem = new javax.swing.JButton();
        jbtnSua = new javax.swing.JButton();
        jcbNameSearch = new javax.swing.JComboBox<>();
        jtfNameSearch = new javax.swing.JTextField();
        jbtnSearch = new javax.swing.JButton();
        jlbStatusSearch = new javax.swing.JLabel();
        jcbStatusSearch = new javax.swing.JComboBox<>();
        jbtnLamMoiSearch = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jlbNcc = new javax.swing.JLabel();
        jtfNcc = new javax.swing.JTextField();
        jlbSdt = new javax.swing.JLabel();
        jtfSdt = new javax.swing.JTextField();
        jlbDiaChi = new javax.swing.JLabel();
        jtfDiaChi = new javax.swing.JTextField();
        jlbStatus = new javax.swing.JLabel();
        jcbStatus = new javax.swing.JComboBox<>();
        jbtnXacNhan = new javax.swing.JButton();
        jbtnHuy = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtbDSNCC = new javax.swing.JTable();

        setLayout(new java.awt.BorderLayout());

        jbtnThem.setText("Thêm");

        jbtnSua.setText("Sửa");

        jcbNameSearch.setModel(
                new javax.swing.DefaultComboBoxModel<>(new String[] { "Tất cả", "Nhà cung cấp", "Số điện thoại" }));

        jbtnSearch.setText("Tìm kiếm");

        jlbStatusSearch.setText("Trạng thái");

        jcbStatusSearch.setModel(
                new javax.swing.DefaultComboBoxModel<>(new String[] { "Tất cả", "Đang hợp tác", "Ngừng hợp tác" }));

        jbtnLamMoiSearch.setText("Làm mới");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jbtnThem)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jbtnSua))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jcbNameSearch, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jtfNameSearch, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jbtnSearch)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jbtnLamMoiSearch)
                                                .addGap(60, 60, 60)
                                                .addComponent(jlbStatusSearch)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jcbStatusSearch, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(284, Short.MAX_VALUE)));
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jbtnThem)
                                        .addComponent(jbtnSua))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jcbNameSearch, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jtfNameSearch, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jbtnSearch)
                                        .addComponent(jlbStatusSearch)
                                        .addComponent(jcbStatusSearch, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jbtnLamMoiSearch))
                                .addContainerGap(30, Short.MAX_VALUE)));

        add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Thông tin nhà cung cấp"));

        jlbNcc.setText("Nhà cung cấp");

        jlbSdt.setText("Số điện thoại");

        jlbDiaChi.setText("Địa chỉ");

        jlbStatus.setText("Trạng thái");

        jcbStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Đang hợp tác", "Ngừng hợp tác" }));

        jbtnXacNhan.setText("Xác nhận");

        jbtnHuy.setText("Hủy");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGroup(jPanel2Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                                jPanel2Layout.createSequentialGroup()
                                                                        .addComponent(jlbNcc)
                                                                        .addGap(18, 18, 18))
                                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                                .addComponent(jlbSdt)
                                                                .addGap(21, 21, 21)))
                                                .addGroup(jPanel2Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                                false)
                                                        .addComponent(jtfSdt)
                                                        .addComponent(jtfNcc, javax.swing.GroupLayout.DEFAULT_SIZE, 180,
                                                                Short.MAX_VALUE))
                                                .addGap(86, 86, 86)
                                                .addGroup(jPanel2Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jlbDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jlbStatus))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanel2Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jcbStatus, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jtfDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(jbtnXacNhan)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jbtnHuy)))
                                .addContainerGap(371, Short.MAX_VALUE)));
        jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jlbNcc)
                                        .addComponent(jtfNcc, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jlbDiaChi)
                                        .addComponent(jtfDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel2Layout
                                                .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(jlbSdt)
                                                .addComponent(jtfSdt, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel2Layout
                                                .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(jlbStatus)
                                                .addComponent(jcbStatus, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jbtnXacNhan)
                                        .addComponent(jbtnHuy))
                                .addContainerGap(30, Short.MAX_VALUE)));

        add(jPanel2, java.awt.BorderLayout.PAGE_END);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Danh sách nhà cung cấp"));
        jPanel3.setLayout(new java.awt.BorderLayout());

        jtbDSNCC.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][] {
                        { null, null, null, null },
                        { null, null, null, null },
                        { null, null, null, null },
                        { null, null, null, null }
                },
                new String[] {
                        "Nhà cung cấp", "Số điện thoại", "Địa chỉ", "Trạng thái"
                }) {
            boolean[] canEdit = new boolean[] {
                    false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        });
        jScrollPane1.setViewportView(jtbDSNCC);
        if (jtbDSNCC.getColumnModel().getColumnCount() > 0) {
            jtbDSNCC.getColumnModel().getColumn(0).setResizable(false);
            jtbDSNCC.getColumnModel().getColumn(1).setResizable(false);
            jtbDSNCC.getColumnModel().getColumn(2).setResizable(false);
            jtbDSNCC.getColumnModel().getColumn(3).setResizable(false);
        }

        jPanel3.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        add(jPanel3, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    // public boolean checkFormFilled() {
    // return (!jtfNcc.getText().isBlank()
    // && !jtfSdt.getText().isBlank()
    // && !jtfDiaChi.getText().isBlank()
    // && jcbStatus.getSelectedIndex() != 0)
    // ? true
    // : false;
    // }

    // // kiem tra sdt co hop le ko ,neu co tra ve 1 ,ko tra ve 0
    // public boolean checkValidSDT(String sdt) {
    // String regex = "^0\\d{9}$";// bat dau = 0 va tong cong co 10 so
    // Pattern pattern = Pattern.compile(regex);
    // Matcher matcher = pattern.matcher(sdt);
    // return matcher.matches();
    // }

    // // kiem tra co trung sdt voi ncc khac ,neu co tra ve 1 ,ko tra ve 0
    // public boolean checkDuplicateSDT(String sdt, String tenNCC) {
    // return BUS.NhaCungCapBUS.getInstance().checkDuplicateSdt(sdt, tenNCC);
    // }

    // public void loadData() {
    // DefaultTableModel tablemodel = ((DefaultTableModel) jtbDSNCC.getModel());
    // tablemodel.setRowCount(0);
    // for (DTO.NhaCungCap dto : BUS.NhaCungCapBUS.getInstance().getAll()) {
    // tablemodel.addRow(new Object[] {
    // dto.getMaNcc(),
    // dto.getTenNcc(),
    // dto.getSdt(),
    // dto.getDiaChi(),
    // dto.getTrangThaiText()
    // });
    // }
    // }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtnHuy;
    private javax.swing.JButton jbtnLamMoiSearch;
    private javax.swing.JButton jbtnSearch;
    private javax.swing.JButton jbtnSua;
    private javax.swing.JButton jbtnThem;
    private javax.swing.JButton jbtnXacNhan;
    private javax.swing.JComboBox<String> jcbNameSearch;
    private javax.swing.JComboBox<String> jcbStatus;
    private javax.swing.JComboBox<String> jcbStatusSearch;
    private javax.swing.JLabel jlbDiaChi;
    private javax.swing.JLabel jlbNcc;
    private javax.swing.JLabel jlbSdt;
    private javax.swing.JLabel jlbStatus;
    private javax.swing.JLabel jlbStatusSearch;
    private javax.swing.JTable jtbDSNCC;
    private javax.swing.JTextField jtfDiaChi;
    private javax.swing.JTextField jtfNameSearch;
    private javax.swing.JTextField jtfNcc;
    private javax.swing.JTextField jtfSdt;
    // End of variables declaration//GEN-END:variables

    public void customComponents() {
        String[][] data = bus.getDsNcc();
        renderDsNcc(data);
        defaultForm();

        jcbStatus.removeAllItems();
        for (String value : NhaCungCap.dsTrangThai) {
            jcbStatus.addItem(value);
        }
        jcbStatusSearch.removeAllItems();
        for (String value : NhaCungCap.dsTrangThaiForFilter) {
            jcbStatusSearch.addItem(value);
        }

        ListSelectionModel model = jtbDSNCC.getSelectionModel();
        model.addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                if (jtbDSNCC.getSelectedRow() != -1) {
                    loadToForm(jtbDSNCC.getSelectedRow());
                }
            }
        });
        jbtnXacNhan.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                jbtnXacNhanActionPerformed(e);
            }
        });
        jbtnThem.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                jbtnThemActionPerformed(e);
            }
        });
        jbtnSua.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                jbtnSuaActionPerformed(e);
            }

        });
        jbtnHuy.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                jbtnHuyActionPerformed(e);
            }
        });
        jbtnSearch.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                jbtnSearchActionPerformed(e);
            }
        });
        jbtnLamMoiSearch.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                jbtnLamMoiSearchActionPerformed(e);
            }
        });
    }

    public void renderDsNcc(String[][] data) {
        jtbDSNCC.setModel(new javax.swing.table.DefaultTableModel(
                data,
                new String[] {
                        "Nhà cung cấp", "Số điện thoại", "Địa chỉ", "Trạng thái"
                }) {
            boolean[] canEdit = new boolean[] {
                    false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        });
        this.revalidate();
    }

    public void jbtnThemActionPerformed(java.awt.event.ActionEvent evt) {
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Thêm nhà cung cấp"));
        clearForm();
        actionForm(0);
        jtbDSNCC.clearSelection();
        jtbDSNCC.setEnabled(false);
    }

    public void jbtnSuaActionPerformed(java.awt.event.ActionEvent evt) {
        if (jtbDSNCC.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(null, "Chưa chọn nhà cung cấp",
                    "Thông báo", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Sửa thông tin nhà cung cấp"));
        actionForm(1);
    }

    public void jbtnXacNhanActionPerformed(java.awt.event.ActionEvent evt) {
        boolean allValid = checkValidData();
        if (allValid) {
            NhaCungCap newNcc = new NhaCungCap(
                0, jtfNcc.getText().trim(),
                jtfSdt.getText().trim(),
                jtfDiaChi.getText().trim(),
                jcbStatus.getSelectedIndex()
            );
            if (jbtnThem.isEnabled()) {
                bus.themNcc(newNcc);
                JOptionPane.showMessageDialog(null, "Thêm nhà cung cấp thành công", 
            "Thông báo", JOptionPane.INFORMATION_MESSAGE);
            } else {
                bus.suaNcc(jtbDSNCC.getSelectedRow(), newNcc);
                JOptionPane.showMessageDialog(null, "Sửa thông tin nhà cung cấp thành công", 
            "Thông báo", JOptionPane.INFORMATION_MESSAGE);
            }
            String[][] data = bus.getDsNcc();
            renderDsNcc(data);
            int index = bus.getIndexNcc(newNcc.getTenNcc());
            jtbDSNCC.setRowSelectionInterval(index, index);
            defaultForm();
        }
    }

    public void jbtnHuyActionPerformed(java.awt.event.ActionEvent evt) {
        if (jbtnThem.isEnabled()) {
            clearForm();
        } else {
            loadToForm(jtbDSNCC.getSelectedRow());
        }
        defaultForm();
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Thông tin nhà cung cấp"));
    }

    public void jbtnSearchActionPerformed(java.awt.event.ActionEvent evt) {
        String type = jcbNameSearch.getSelectedItem().toString();
        String value = jtfNameSearch.getText().trim();
        String statusText = jcbStatusSearch.getSelectedItem().toString();
        String[][] data = bus.getFilterdDsNcc(type, value, statusText);
        renderDsNcc(data);
        if (jbtnThem.isEnabled() && jbtnSua.isEnabled()) {
            clearForm();
        } else if (jbtnSua.isEnabled()) {
            clearForm();
            defaultForm();
        }
    }

    public void jbtnLamMoiSearchActionPerformed(java.awt.event.ActionEvent evt) {
        jcbNameSearch.setSelectedIndex(0);
        jtfNameSearch.setText("");
        jcbStatusSearch.setSelectedIndex(0);
        String[][] data = bus.getDsNcc();
        renderDsNcc(data);
    }

    public void loadToForm(int row) {
        NhaCungCap ncc = bus.getSelectedNcc(row);
        if (ncc != null) {
            jtfNcc.setText(ncc.getTenNcc());
            jtfSdt.setText(ncc.getSdt());
            jtfDiaChi.setText(ncc.getDiaChi());
            jcbStatus.setSelectedItem(ncc.getTrangThaiText());
        }
    }

    public void defaultForm() {
        jbtnThem.setEnabled(true);
        jbtnSua.setEnabled(true);
        jtbDSNCC.setEnabled(true);
        jtfNcc.setEnabled(false);
        jtfSdt.setEnabled(false);
        jtfDiaChi.setEnabled(false);
        jcbStatus.setEnabled(false);
        jbtnXacNhan.setEnabled(false);
        jbtnHuy.setEnabled(false);
    }

    public void actionForm(int type) {
        switch (type) {
            case 0:
                jbtnSua.setEnabled(false);
                jcbStatus.setSelectedIndex(1);
                break;
            case 1:
                jbtnThem.setEnabled(false);
                break;
        }
        jtfNcc.setEnabled(true);
        jtfSdt.setEnabled(true);
        jtfDiaChi.setEnabled(true);
        jcbStatus.setEnabled(true);
        jbtnXacNhan.setEnabled(true);
        jbtnHuy.setEnabled(true);
    }

    public void clearForm() {
        jtfNcc.setText("");
        jtfSdt.setText("");
        jtfDiaChi.setText("");
        jcbStatus.setSelectedIndex(1);
    }

    public boolean checkValidData () {
        if (jtfNcc.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Tên nhà cung cấp là bắt buộc", 
            "Thông báo", JOptionPane.WARNING_MESSAGE);
            return false;
        }
        NhaCungCap ncc = bus.getNccByTen(jtfNcc.getText().trim());
        if (ncc != null) {
            if (jbtnThem.isEnabled()) {
                JOptionPane.showMessageDialog(null, "Tên nhà cung cấp đã tồn tại", 
                "Thông báo", JOptionPane.WARNING_MESSAGE);
                return false;
            }
            if (jbtnSua.isEnabled()) {
                if (ncc.getMaNcc() != bus.getSelectedNcc(jtbDSNCC.getSelectedRow()).getMaNcc()) {
                    JOptionPane.showMessageDialog(null, "Tên nhà cung cấp đã tồn tại", 
                "Thông báo", JOptionPane.WARNING_MESSAGE);
                    return false;
                };
            }
        }
        if (jtfSdt.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Số điện thoại là bắt buộc", 
            "Thông báo", JOptionPane.WARNING_MESSAGE);
            return false;
        }
        String regex = "^0\\d{9,10}$";
        Pattern pattern = Pattern.compile(regex);
        Matcher matcher = pattern.matcher(jtfSdt.getText().trim());
        if (!matcher.matches()) {
            JOptionPane.showMessageDialog(null, "Số điện thoại không hợp lệ", 
            "Thông báo", JOptionPane.WARNING_MESSAGE);
            return false;
        };
        ncc = bus.getNccBySdt(jtfSdt.getText().trim());
        if (ncc != null) {
            if (jbtnThem.isEnabled()) {
                JOptionPane.showMessageDialog(null, "Số điện thoại đã tồn tại", 
                "Thông báo", JOptionPane.WARNING_MESSAGE);
                return false;
            }
            if (jbtnSua.isEnabled()) {
                if (ncc.getMaNcc() != bus.getSelectedNcc(jtbDSNCC.getSelectedRow()).getMaNcc()) {
                    JOptionPane.showMessageDialog(null, "Số điện thoại đã tồn tại", 
                "Thông báo", JOptionPane.WARNING_MESSAGE);
                    return false;
                };
            }
        }
        return true;
    }
}
