/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import java.awt.Component;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.nio.ByteBuffer;
import java.nio.charset.StandardCharsets;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableModel;

import DTO.NhanVien;
import DTO.SanPham;
import DAO.SanPhamDAO;
import BUS.SanPhamBUS;
import BUS.TaiKhoanBus;

/**
 *
 * @author BomPC
 */
public class SanPhamGUI extends javax.swing.JPanel {

    /**
     * Creates new form SanPhamView
     */
	private SanPhamBUS SanPhamBUS = null;
    private SanPham SanPham = null;
    private String[] kichCoList = null;
    private javax.swing.table.DefaultTableModel model;
    private ArrayList<SanPham> checkList;
    private List<JTextField> requiredFieldList = new ArrayList<>();
    private String formStatus = "";
    private String dupFlag="";
    
    public SanPhamGUI() {
    	SanPhamBUS = new SanPhamBUS();
    	model = new DefaultTableModel(new Object[] {"Mã","Sản phẩm","Giá bán (VNĐ)","Số lượng","Trạng thái"},0){
            boolean[] canEdit = new boolean [] {
                    false, false, false, false, false
                };

                public boolean isCellEditable(int rowIndex, int columnIndex) {
                    return canEdit [columnIndex];
                }
            };
        initComponents();
        editComponents();
        setTable();
        defaultStatus();
        actionEvent();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtbDSSP = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel5 = new javax.swing.JPanel();
        jlbMaSPCT = new javax.swing.JLabel();
        jlbChatLieuCT = new javax.swing.JLabel();
        jlbMauSacCT = new javax.swing.JLabel();
        jlbKichCoCT = new javax.swing.JLabel();
        jlbGiaBanCT = new javax.swing.JLabel();
        jlbSoLuongCT = new javax.swing.JLabel();
        jlbTrangThaiCT = new javax.swing.JLabel();
        jlbImageCT = new javax.swing.JLabel();
        jlbSanPhamCT = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jbtnThem = new javax.swing.JButton();
        jbtnSua = new javax.swing.JButton();
        jbtnXoa = new javax.swing.JButton();
        jcbNameSearchType = new javax.swing.JComboBox<>();
        jtfNameSearch = new javax.swing.JTextField();
        jlbStatusSearch = new javax.swing.JLabel();
        jcbStatusSearch = new javax.swing.JComboBox<>();
        jbtnSearch = new javax.swing.JButton();
        jbtnClearFilterForm = new javax.swing.JButton();
        jpnFormSP = new javax.swing.JPanel();
        jlbMa = new javax.swing.JLabel();
        jtfMa = new javax.swing.JTextField();
        jlbChatLieu = new javax.swing.JLabel();
        jtfChatLieu = new javax.swing.JTextField();
        jlbSoLuong = new javax.swing.JLabel();
        jtfSoLuong = new javax.swing.JTextField();
        jlbSanPham = new javax.swing.JLabel();
        jtfSanPham = new javax.swing.JTextField();
        jlbMauSac = new javax.swing.JLabel();
        jtfMauSac = new javax.swing.JTextField();
        jlbGiaBan = new javax.swing.JLabel();
        jtfGiaBan = new javax.swing.JTextField();
        jlbStatus = new javax.swing.JLabel();
        jcbStatus = new javax.swing.JComboBox<>();
        jlbHinhAnh = new javax.swing.JLabel();
        jtfHinhAnh = new javax.swing.JTextField();
        jlbKichCo = new javax.swing.JLabel();
        jcbKichCo = new javax.swing.JComboBox<>();
        jbtnXacNhan = new javax.swing.JButton();
        jbtnHuy = new javax.swing.JButton();
        jbtnLamMoi = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new java.awt.BorderLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Danh sách sản phẩm"));
        jPanel2.setLayout(new java.awt.BorderLayout());

        jtbDSSP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã", "Sản phẩm", "Giá bán", "Số lượng", "Trạng thái"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jtbDSSP);
        if (jtbDSSP.getColumnModel().getColumnCount() > 0) {
            jtbDSSP.getColumnModel().getColumn(0).setResizable(false);
            jtbDSSP.getColumnModel().getColumn(1).setResizable(false);
            jtbDSSP.getColumnModel().getColumn(2).setResizable(false);
            jtbDSSP.getColumnModel().getColumn(3).setResizable(false);
            jtbDSSP.getColumnModel().getColumn(4).setResizable(false);
        }

        jPanel2.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel3.setPreferredSize(new java.awt.Dimension(400, 427));
        jPanel3.setLayout(new java.awt.BorderLayout());

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("CHI TIẾT SẢN PHẨM");
        jLabel2.setPreferredSize(new java.awt.Dimension(108, 24));
        jPanel3.add(jLabel2, java.awt.BorderLayout.PAGE_START);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setAutoscrolls(true);
        jPanel1.setPreferredSize(new java.awt.Dimension(400, 411));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jlbMaSPCT.setText("Mã sản phẩm:");

        jlbChatLieuCT.setText("Chất liệu:");

        jlbMauSacCT.setText("Màu sắc: ");

        jlbKichCoCT.setText("Kích cỡ:");

        jlbGiaBanCT.setText("Giá bán:");

        jlbSoLuongCT.setText("Số lượng:");

        jlbTrangThaiCT.setText("Trạng thái:");

        jlbImageCT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/362262966_1023992471955085_8868555814812732925_n.jpg"))); // NOI18N
        jlbImageCT.setOpaque(true);
        jlbImageCT.setPreferredSize(new java.awt.Dimension(200, 220));

        jlbSanPhamCT.setText("Sản phẩm:");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlbTrangThaiCT)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jlbMauSacCT, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                            .addComponent(jlbGiaBanCT, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlbSoLuongCT)))
                .addContainerGap(161, Short.MAX_VALUE))
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addGap(112, 112, 112)
                            .addComponent(jlbImageCT, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addGap(6, 6, 6)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel5Layout.createSequentialGroup()
                                    .addGap(169, 169, 169)
                                    .addComponent(jlbKichCoCT))
                                .addComponent(jlbMaSPCT)
                                .addComponent(jlbChatLieuCT)
                                .addComponent(jlbSanPhamCT))))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(309, Short.MAX_VALUE)
                .addComponent(jlbMauSacCT)
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbGiaBanCT)
                    .addComponent(jlbSoLuongCT))
                .addGap(18, 18, 18)
                .addComponent(jlbTrangThaiCT)
                .addGap(16, 16, 16))
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jlbImageCT, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(jlbMaSPCT)
                    .addGap(18, 18, 18)
                    .addComponent(jlbSanPhamCT)
                    .addGap(57, 57, 57)
                    .addComponent(jlbChatLieuCT)
                    .addGap(18, 18, 18)
                    .addComponent(jlbKichCoCT)
                    .addContainerGap(84, Short.MAX_VALUE)))
        );

        jScrollPane2.setViewportView(jPanel5);

        jPanel1.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        jPanel3.add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel3, java.awt.BorderLayout.LINE_END);

        add(jPanel2, java.awt.BorderLayout.CENTER);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jbtnThem.setText("Thêm");

        jbtnSua.setText("Sửa");

        jbtnXoa.setText("Xóa");

        jcbNameSearchType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tất cả", "Mã", "Sản phẩm" }));

        jlbStatusSearch.setText("Trạng thái");

        jcbStatusSearch.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jbtnSearch.setText("Tìm kiếm");

        jbtnClearFilterForm.setText("Làm mới");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jbtnThem)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtnSua)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtnXoa))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jcbNameSearchType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfNameSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtnSearch)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtnClearFilterForm)
                        .addGap(120, 120, 120)
                        .addComponent(jlbStatusSearch)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jcbStatusSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(306, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnThem)
                    .addComponent(jbtnSua)
                    .addComponent(jbtnXoa))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbNameSearchType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfNameSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlbStatusSearch)
                    .addComponent(jcbStatusSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnSearch)
                    .addComponent(jbtnClearFilterForm))
                .addContainerGap(55, Short.MAX_VALUE))
        );

        add(jPanel4, java.awt.BorderLayout.PAGE_START);

        jpnFormSP.setBackground(new java.awt.Color(255, 255, 255));
        jpnFormSP.setBorder(javax.swing.BorderFactory.createTitledBorder("Thông tin sản phẩm"));
        jpnFormSP.setPreferredSize(new java.awt.Dimension(1004, 200));

        jlbMa.setText("Mã");

        jlbChatLieu.setText("Chất liệu");

        jtfChatLieu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfChatLieuActionPerformed(evt);
            }
        });

        jlbSoLuong.setText("Số lượng");

        jlbSanPham.setText("Sản phẩm");

        jlbMauSac.setText("Màu sắc");

        jlbGiaBan.setText("Giá bán");

        jlbStatus.setText("Trạng thái");

        jcbStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jlbHinhAnh.setText("Hình ảnh");

        jlbKichCo.setText("Kích cỡ");

        jcbKichCo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jbtnXacNhan.setText("Xác nhận");

        jbtnHuy.setText("Hủy");

        jbtnLamMoi.setText("Làm mới");

        javax.swing.GroupLayout jpnFormSPLayout = new javax.swing.GroupLayout(jpnFormSP);
        jpnFormSP.setLayout(jpnFormSPLayout);
        jpnFormSPLayout.setHorizontalGroup(
            jpnFormSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnFormSPLayout.createSequentialGroup()
                .addGroup(jpnFormSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnFormSPLayout.createSequentialGroup()
                        .addGroup(jpnFormSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpnFormSPLayout.createSequentialGroup()
                                .addGroup(jpnFormSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlbHinhAnh)
                                    .addComponent(jlbMa))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jpnFormSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jpnFormSPLayout.createSequentialGroup()
                                        .addGroup(jpnFormSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jtfSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jtfMa, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(74, 74, 74)
                                        .addGroup(jpnFormSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jlbChatLieu)
                                            .addComponent(jlbMauSac))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jpnFormSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jtfChatLieu, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                            .addComponent(jtfMauSac)))
                                    .addComponent(jtfHinhAnh)))
                            .addComponent(jlbSanPham))
                        .addGap(74, 74, 74)
                        .addGroup(jpnFormSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jlbGiaBan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jlbKichCo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jpnFormSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfGiaBan, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jcbKichCo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(74, 74, 74)
                        .addGroup(jpnFormSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jlbStatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jlbSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jpnFormSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jcbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jpnFormSPLayout.createSequentialGroup()
                        .addComponent(jbtnXacNhan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtnLamMoi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtnHuy)))
                .addGap(0, 6, Short.MAX_VALUE))
        );
        jpnFormSPLayout.setVerticalGroup(
            jpnFormSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnFormSPLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpnFormSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbMa)
                    .addComponent(jtfMa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlbChatLieu)
                    .addComponent(jtfChatLieu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlbGiaBan)
                    .addComponent(jlbSoLuong)
                    .addComponent(jtfSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfGiaBan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpnFormSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbSanPham)
                    .addComponent(jtfSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlbMauSac)
                    .addComponent(jtfMauSac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlbKichCo)
                    .addComponent(jcbKichCo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlbStatus)
                    .addComponent(jcbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpnFormSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbHinhAnh)
                    .addComponent(jtfHinhAnh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpnFormSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnXacNhan)
                    .addComponent(jbtnHuy)
                    .addComponent(jbtnLamMoi))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        add(jpnFormSP, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents

    private void jtfChatLieuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfChatLieuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfChatLieuActionPerformed
    
    public void editComponents() {
    	jlbMa.setText("Mã*");
    	jlbSanPham.setText("Sản phẩm*");
    	jlbGiaBan.setText("Giá bán*");
    	jcbKichCo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "S","M","L","XL","XLL" }));
    	jcbStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {"Ngừng bán", "Chuẩn bị bán", "Đang bán"}));
    	jcbKickCoSearch.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "S","M","L","XL","XLL" }));
    	jcbStatusSearch.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {"Ngừng bán", "Chuẩn bị bán", "Đang bán"}));
    	
    }
    
  //SET LIST FORM'S STATUS
    public boolean setListFormStatus(JPanel panel, Boolean status) {
    	for (Component cp : panel.getComponents() ){
            if (!(cp instanceof JButton))
    			cp.setEnabled(status);
    	}
    	return status;
    }
  // GET LIST FORM
    public SanPham getListForm() {
    	 String maSP = jtfMa.getText();
    	 String tenSP = jtfSanPham.getText();
    	 String chatlieu = jtfChatLieu.getText();
    	 String mausac = jtfMauSac.getText();
    	 String kichco = jcbKichCo.getSelectedItem().toString();
    	 int giaban = Integer.parseInt(jtfGiaBan.getText());
    	 int soluong = Integer.parseInt(jtfSoLuong.getText());
    	 String trangthai = jcbStatus.getSelectedItem().toString();
    	 int status=0;
    	 switch(trangthai) {
    	 case "Ngừng bán": status=0; break;
    	 case "Chuẩn bị bán": status=1; break;
    	 case "Đang bán": status=2; break;
    	 }
    	 String hinhanh = jtfHinhAnh.getText();
    	 SanPham sp = new SanPham(maSP,tenSP,chatlieu,kichco,mausac,giaban,soluong,hinhanh,status);
    	 System.out.println(maSP+" "+tenSP+" "+chatlieu+" "+kichco+" "+mausac+" "+giaban+" "+soluong+" "+hinhanh+" "+status);
    	 return sp;
    }
  // GET SEARCH FORM
    public ArrayList<Object> getSearchForm() {
   	 String name = jtfNameSearch.getText();
   	 String chatlieu = jtfChatLieuSearch.getText();
   	 String mausac = jtfMauSacSearch.getText();
   	 String trangthai = jcbStatusSearch.getSelectedItem().toString();
   	 String kichco = jcbKickCoSearch.getSelectedItem().toString();
   	 int status=0;
   	 switch(trangthai) {
   	 case "Ngừng bán": status=0; break;
   	 case "Chuẩn bị bán": status=1; break;
   	 case "Đang bán": status=2; break;
   	 }
   	 ArrayList<Object> search = new ArrayList<>((Arrays.asList(name,chatlieu,mausac,kichco,status)));
   	 System.out.println(name+" "+chatlieu+" "+mausac+" "+kichco+" "+status);
   	 return search;
   }
  // CLEAR LIST FORM 
    public void clearForm() {
    	for (Component cp : jpnFormSP.getComponents() ){
            if ((cp instanceof JTextField) && ( ((JTextField) cp).isEnabled() ) )
    			((JTextField) cp).setText("");
    	}
    }
   //DEFAULT DETAILS FORM
    public void resetDetailForm() {
    	jlbMaSPCT.setText("Mã sản phẩm:");
   		jlbSanPhamCT.setText("Sản phẩm:");
   		jlbChatLieuCT.setText("Chất liệu:");
   		jlbMauSacCT.setText("Màu sắc:");
   		jlbKichCoCT.setText("Kích cỡ:");
   		jlbGiaBanCT.setText("Giá bán:");
   		jlbSoLuongCT.setText("Số lượng:");
   		jlbTrangThaiCT.setText("Trạng thái:");
    }
   //SET DETAILS FORM
    public void setDetailForm() {
    	resetDetailForm();
    	int selectedRow = jtbDSSP.getSelectedRow();
		 if (selectedRow != -1) {
			 String maSP = jtbDSSP.getValueAt(selectedRow,0).toString();
			 jlbMaSPCT.setText(jlbMaSPCT.getText() + " " + maSP);
			 SanPham sp = this.SanPhamBUS.getChiTiet(maSP);
			 jlbSanPhamCT.setText(jlbSanPhamCT.getText() + " " + sp.getTenSP());
			 jlbChatLieuCT.setText(jlbChatLieuCT.getText() + " " + sp.getChatLieu());
			 jlbMauSacCT.setText(jlbMauSacCT.getText() + " " + sp.getMauSac());
			 jlbKichCoCT.setText(jlbKichCoCT.getText() + " " + sp.getKichCo());
			 jlbGiaBanCT.setText(jlbGiaBanCT.getText() + " " + sp.getGiaBan());
			 jlbSoLuongCT.setText(jlbSoLuongCT.getText() + " " + sp.getSoLuong());
			 jlbTrangThaiCT.setText(jlbTrangThaiCT.getText() + " " + sp.getTrangThaiText());
		 }	 
    }
    
   //SET TABLE
    public void setTable() {
    	model.setRowCount(0);
    	ArrayList<SanPham> sanPhamList = this.SanPhamBUS.getSanPham();
    	checkList = sanPhamList;
    	for (SanPham sp : checkList ) {
    		Object[] column = new Object[model.getColumnCount()];
            column[0] = sp.getMaSP();
            column[1] = sp.getTenSP();
            column[2] = sp.getGiaBan();
            column[3] = sp.getSoLuong();
            String status = sp.getTrangThaiText();
            column[4] = status;
            this.model.addRow(column);
    	}
    	jtbDSSP.setModel(model);
    }
    
   //GET TABLE
    public void getTable() {
    	int selectedRow = jtbDSSP.getSelectedRow();
		 if (selectedRow != -1) {
			 jtfMa.setText(jtbDSSP.getValueAt(selectedRow,0).toString());
			 SanPham sp = this.SanPhamBUS.getChiTiet(jtfMa.getText());
			 jtfSanPham.setText(jtbDSSP.getValueAt(selectedRow,1).toString());
			 jtfChatLieu.setText(sp.getChatLieu());
			 jtfMauSac.setText(sp.getMauSac());
			 jtfHinhAnh.setText(sp.getMauSac());
			 jtfGiaBan.setText(String.valueOf(sp.getGiaBan()));
			 jtfSoLuong.setText(String.valueOf(sp.getSoLuong()));
			 jcbKichCo.setSelectedItem(sp.getKichCo().toString());
			 jcbStatus.setSelectedItem(jtbDSSP.getValueAt(selectedRow,4).toString());
		 }
    }
    
   //DEFAULT STATUS
    public void defaultStatus() {
    	jpnFormSP.setBorder(javax.swing.BorderFactory.createTitledBorder("Thông tin sản phẩm"));
    	jtbDSSP.setRowSelectionAllowed(true);
    	jbtnXacNhan.setEnabled(false);
    	jbtnHuy.setEnabled(false);
    	jbtnXoa.setEnabled(true);
    	jbtnThem.setEnabled(true);
    	jbtnSua.setEnabled(true);
    	jbtnLamMoi.setEnabled(false);
    	jbtnXacNhan.setEnabled(false);
    	clearForm();
    	setListFormStatus(jpnFormSP,false);
    }
    
    
    public void actionEvent() {
    	//CHECK REQUIRED FIELDS
    	requiredFieldList.add(jtfMa);
        requiredFieldList.add(jtfSanPham);
        requiredFieldList.add(jtfGiaBan);
        DocumentListener addListener = new DocumentListener() {
			 	@Override
			    public void removeUpdate(DocumentEvent e) { changedUpdate(e); }
			    @Override
			    public void insertUpdate(DocumentEvent e) { changedUpdate(e); }
			    @Override
			    public void changedUpdate(DocumentEvent e) {
			        boolean canEnable = true;
			        for (JTextField tf : requiredFieldList) {
			            if (tf.getText().isEmpty() ) 
				                canEnable = false;
			        }
			        if(formStatus.equals("edit") || formStatus.equals("add"))
			        	jbtnXacNhan.setEnabled(canEnable);
			        else jbtnXacNhan.setEnabled(false);
			    }	
		 };
		 for (JTextField tf : requiredFieldList)
			 tf.getDocument().addDocumentListener(addListener); 
		 
    	//SELECT TABLE
    	jtbDSSP.addMouseListener(new java.awt.event.MouseAdapter() {
			 @Override
			    public void mouseClicked(java.awt.event.MouseEvent evt) {
				 jbtnXacNhan.setEnabled(false);
				 if ( jbtnThem.isEnabled() && jbtnSua.isEnabled() ) {
					 setListFormStatus(jpnFormSP,true);
					 clearForm();
					 setDetailForm();
					 getTable();
					 setListFormStatus(jpnFormSP,false);
					 //DELETE STATUS
					 jbtnXoa.addActionListener(new ActionListener() {
						 public void actionPerformed(ActionEvent e) {
							 JOptionPane ask = new JOptionPane();
								int choice = JOptionPane.showConfirmDialog(ask,"Bạn có chắc muốn xoá?", "XOÁ SẢN PHẨM", JOptionPane.YES_NO_OPTION); 
								if(choice==JOptionPane.YES_OPTION) {
									SanPhamBUS.deleteSanPham(jtfMa.getText().toString());
									JOptionPane.showMessageDialog(null,"Xoá sản phẩm thành công!");
									ask.setValue(false);  
									setTable();
									jbtnXoa.removeActionListener(this);
								}
							 else if(choice==JOptionPane.NO_OPTION) {
								 ask.setValue(false); 
								 jbtnXoa.removeActionListener(this);
							 }
			    		 } 
					 });
					//CANCEL BUTTON
		    		jbtnHuy.addActionListener(new ActionListener() {
		    			public void actionPerformed(ActionEvent e) {
		    				setListFormStatus(jpnFormSP,true);
		    				defaultStatus();
		    			}
		    		});
				 }
			 }
		 });
    	
    	//CHECK FORM
		 jtfMa.addFocusListener(new FocusListener() {
			 @Override
	            public void focusGained(FocusEvent e) {
	            }
			 @Override
	            public void focusLost(FocusEvent e) {
	                dupFlag = SanPhamBUS.checkDuplicate(jtfMa.getText());
	                if(dupFlag.equals("dup")) {
	                	JOptionPane.showMessageDialog(null,"Mã bị trùng, hãy đổi mã khác!","WARNING",JOptionPane.ERROR_MESSAGE);
	                	jtfMa.requestFocus();
	                }
			 }
		 });
		 jtfGiaBan.addFocusListener(new FocusListener() {
			 @Override
	            public void focusGained(FocusEvent e) {
	            }
			 @Override
	            public void focusLost(FocusEvent e) {
				 	try {
				 		Integer.parseInt( jtfGiaBan.getText() );
				 	}
				 	catch( Exception convertError ) {
				 		if(!(jtfGiaBan.getText().isEmpty())) {
				 			JOptionPane.showMessageDialog(null,"Giá bán phải là số nguyên!","WARNING",JOptionPane.ERROR_MESSAGE);
				 			jtfGiaBan.requestFocus();
				 		}
				 	}
			 }
		 });
		 
    	//ADD STATUS
    	 jbtnThem.addActionListener(new ActionListener() {
    		 public void actionPerformed(ActionEvent e) {
    			 formStatus = "add";
    			 setListFormStatus(jpnFormSP,true);
    			 clearForm();
    			 jpnFormSP.setBorder(javax.swing.BorderFactory.createTitledBorder("Thêm sản phẩm mới"));
    			 jbtnSua.setEnabled(false);
    			 jbtnHuy.setEnabled(true);
    			 jbtnXoa.setEnabled(false);
    			 jbtnThem.setEnabled(true);
    			 jbtnLamMoi.setEnabled(true);
    			 jtbDSSP.setCellSelectionEnabled(false);
    			 jtbDSSP.setFocusable(false);
    			 jtbDSSP.setOpaque(false);
    			 jtfSoLuong.setEnabled(false);
    			 jtfSoLuong.setText("0");
    			 
    			 //ADD TO DATABASE 
    			 jbtnXacNhan.addActionListener(new ActionListener() {
    	    		 public void actionPerformed(ActionEvent e) {
    	    				SanPham sp = getListForm();
    	    				SanPhamBUS.addSanPham(sp, dupFlag);
    	    				//ADD TO TABLE
    	    				setTable();
    	    				int lastRowIndex = model.getRowCount()-1;
    	    	            if (lastRowIndex >= 0) {
    	    	                jtbDSSP.setRowSelectionInterval(lastRowIndex, lastRowIndex);
    	    	                jtbDSSP.scrollRectToVisible(jtbDSSP.getCellRect(lastRowIndex, 0, true));
    	    	            }
    	    		 }
    	    		 
    			 });
    			 //CLEAR BUTTON
    			 jbtnLamMoi.addActionListener(new ActionListener() {
    	    		 public void actionPerformed(ActionEvent e) {
    	    			 clearForm();
    	    		 }
    			 });
    			 //CANCEL BUTTON
    			 jbtnHuy.addActionListener(new ActionListener() {
    	    		 public void actionPerformed(ActionEvent e) {
    	    			 formStatus = "default";
    	    			 defaultStatus();
    	    		 }
    			 });
    		 }
    	 });
    	 
    	 //EDIT STATUS
    	 jbtnSua.addActionListener(new ActionListener() {
    		 public void actionPerformed(ActionEvent e) {
    			 formStatus = "edit";
    			 setListFormStatus(jpnFormSP,true);
    			 jpnFormSP.setBorder(javax.swing.BorderFactory.createTitledBorder("Sửa chi tiết sản phẩm"));
    			 jbtnThem.setEnabled(false);
    			 jbtnXoa.setEnabled(false);
    			 jbtnHuy.setEnabled(true);
    			 jtfSoLuong.setEnabled(false);
    			 jtfMa.setEnabled(false);
    			 jbtnLamMoi.setEnabled(true);
    			 //SELECT TABLE ROW
    			 jtbDSSP.addMouseListener(new java.awt.event.MouseAdapter() {
    				 @Override
    				    public void mouseClicked(java.awt.event.MouseEvent evt) {
    					 if(jbtnSua.isEnabled()) {
    						 setDetailForm();
    						 getTable();
    					 }
    				 }
    			 });
    			//UPDATE TO DATABASE 
    			 jbtnXacNhan.addActionListener(new ActionListener() {
    	    		 public void actionPerformed(ActionEvent e) {
    	    				SanPham sp = getListForm();
    	    				SanPhamBUS.updateSanPham(sp);
    	    				//ADD TO TABLE
    	    				setTable();
    	    				int lastRowIndex = model.getRowCount()-1;
    	    	            if (lastRowIndex >= 0) {
    	    	                jtbDSSP.setRowSelectionInterval(lastRowIndex, lastRowIndex);
    	    	                jtbDSSP.scrollRectToVisible(jtbDSSP.getCellRect(lastRowIndex, 0, true));
    	    	            }
    	    		 }
    	    		 
    			 });
    			//CLEAR BUTTON
    			 jbtnLamMoi.addActionListener(new ActionListener() {
    	    		 public void actionPerformed(ActionEvent e) {
    	    			 clearForm();
    	    		 }
    			 });
    			 //CANCEL BUTTON
    			 jbtnHuy.addActionListener(new ActionListener() {
    	    		 public void actionPerformed(ActionEvent e) {
    	    			 formStatus = "default";
    	    			 jtfMa.setEnabled(true);
    	    			 jtfSoLuong.setEnabled(true);
    	    			 defaultStatus();
    	    		 }
    			 });
    		 }
    	 });
    	 //SEARCH BAR
    	 jbtnSearch.addActionListener(new ActionListener() {
    		 public void actionPerformed(ActionEvent e) {
    			 String type = jcbNameSearchType.getSelectedItem().toString();
    			 ArrayList<Object> searchQuery = getSearchForm();
    			 ArrayList<SanPham> spSearch = SanPhamBUS.searchSanPham(type,searchQuery);
    			 
    		 }
    	 });
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jbtnClearFilterForm;
    private javax.swing.JButton jbtnHuy;
    private javax.swing.JButton jbtnLamMoi;
    private javax.swing.JButton jbtnSearch;
    private javax.swing.JButton jbtnSua;
    private javax.swing.JButton jbtnThem;
    private javax.swing.JButton jbtnXacNhan;
    private javax.swing.JButton jbtnXoa;
    private javax.swing.JComboBox<String> jcbKichCo;
    private javax.swing.JComboBox<String> jcbNameSearchType;
    private javax.swing.JComboBox<String> jcbStatus;
    private javax.swing.JComboBox<String> jcbStatusSearch;
    private javax.swing.JLabel jlbChatLieu;
    private javax.swing.JLabel jlbChatLieuCT;
    private javax.swing.JLabel jlbGiaBan;
    private javax.swing.JLabel jlbGiaBanCT;
    private javax.swing.JLabel jlbHinhAnh;
    private javax.swing.JLabel jlbImageCT;
    private javax.swing.JLabel jlbKichCo;
    private javax.swing.JLabel jlbKichCoCT;
    private javax.swing.JLabel jlbMa;
    private javax.swing.JLabel jlbMaSPCT;
    private javax.swing.JLabel jlbMauSac;
    private javax.swing.JLabel jlbMauSacCT;
    private javax.swing.JLabel jlbSanPham;
    private javax.swing.JLabel jlbSanPhamCT;
    private javax.swing.JLabel jlbSoLuong;
    private javax.swing.JLabel jlbSoLuongCT;
    private javax.swing.JLabel jlbStatus;
    private javax.swing.JLabel jlbStatusSearch;
    private javax.swing.JLabel jlbTrangThaiCT;
    private javax.swing.JPanel jpnFormSP;
    private javax.swing.JTable jtbDSSP;
    private javax.swing.JTextField jtfChatLieu;
    private javax.swing.JTextField jtfGiaBan;
    private javax.swing.JTextField jtfHinhAnh;
    private javax.swing.JTextField jtfMa;
    private javax.swing.JTextField jtfMauSac;
    private javax.swing.JTextField jtfNameSearch;
    private javax.swing.JTextField jtfSanPham;
    private javax.swing.JTextField jtfSoLuong;
    // End of variables declaration//GEN-END:variables
    
}
