/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.GridLayout;
import java.time.LocalDateTime;
import java.time.ZoneId;
import java.util.ArrayList;
import java.util.Date;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.axis.Axis;
import org.jfree.chart.axis.NumberAxis;
import org.jfree.chart.axis.SymbolAxis;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.chart.plot.XYPlot;
import org.jfree.chart.renderer.category.BarRenderer;
import org.jfree.chart.renderer.xy.XYSplineRenderer;
import org.jfree.data.category.DefaultCategoryDataset;
import org.jfree.data.xy.XYDataset;
import org.jfree.data.xy.XYSeries;
import org.jfree.data.xy.XYSeriesCollection;

import BUS.ThongKeDoanhThuBUS;
import DTO.HoaDonBan;
import java.text.SimpleDateFormat;
import java.time.format.DateTimeFormatter;
import java.util.Locale;
import org.jfree.chart.axis.CategoryAxis;
import org.jfree.chart.axis.CategoryLabelPosition;
import org.jfree.chart.axis.CategoryLabelPositions;
import org.jfree.chart.renderer.category.LineAndShapeRenderer;

/**
 *
 * @author Windows
 */
public class ThongKeDoanhThuGUI extends javax.swing.JPanel {

    private ThongKeDoanhThuBUS revenueStatisBus;

    /**
     * Creates new form ThongKeDoanhThu
     */
    public ThongKeDoanhThuGUI() {
        initComponents();
        createChartHist();
        createChartSpline();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    public void createChartHist() {
        datasethist = new DefaultCategoryDataset();
        datasethist.setValue(0, "Ngày", "00/00/0000");
        charthist = ChartFactory.createBarChart("", "Ngày", "Doanh thu", datasethist, PlotOrientation.VERTICAL, false,
                false, false);
        CategoryPlot categoryplot = charthist.getCategoryPlot();
        categoryplot.setBackgroundPaint(new Color(255, 250, 205));
        BarRenderer renderer = (BarRenderer) categoryplot.getRenderer();
        renderer.setSeriesPaint(0, new Color(135, 206, 250));

        ChartPanel histpanel = new ChartPanel(charthist);
        jpanelhist.removeAll();
        jpanelhist.add(histpanel);
        jpanelhist.revalidate();
        jpanelhist.repaint();
    }

    public void createChartSpline() {
        XYSeries series = new XYSeries("");
        series.add(0, 0);
//        series.add(0, 0);
//        series.add(0, 0);
//        series.add(0, 0);
//        series.add(0, 0);
//        series.add(0, 0);
//        series.add(0, 0);
//        series.add(0, 0);
//        series.add(0, 0);
//        series.add(0, 0);
//        series.add(0, 0);
//        series.add(0, 0);
        datasetspline = new XYSeriesCollection(series);
        String[] labels = new String[series.getItemCount()];
        labels[0] = "00/00/0000";
//        labels[1] = "2/1/2023";
//        labels[2] = "3/1/2023";
//        labels[3] = "4/1/2023";
//        labels[4] = "5/1/2023";
//        labels[5] = "6/1/2023";
//        labels[6] = "7/1/2023";
//        labels[7] = "8/1/2023";
//        labels[8] = "9/1/2023";
//        labels[9] = "10/1/2023";
//        labels[10] = "11/1/2023";
//        labels[11] = "12/1/2023";
        NumberAxis domain = new SymbolAxis("Ngày", labels);
        NumberAxis range = new NumberAxis("Doanh thu");
        XYSplineRenderer r = new XYSplineRenderer(8);
        XYPlot xyplot = new XYPlot(datasetspline, domain, range, r);

        chartspline = new JFreeChart(xyplot);
        chartspline.getLegend().setVisible(false);
        ChartPanel chartPanel = new ChartPanel(chartspline);
        jpanelspline.removeAll();
        jpanelspline.add(chartPanel);
        jpanelspline.revalidate();
        jpanelspline.repaint();

    }

    // <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jpanelleft = new javax.swing.JPanel();
		jpanelhist = new javax.swing.JPanel();
		jpanelspline = new javax.swing.JPanel();
		jpanelright = new javax.swing.JPanel();
		jpanelrightup = new javax.swing.JPanel();
		jLabel = new javax.swing.JLabel();
		jScrollPane1 = new javax.swing.JScrollPane();
		jTable1 = new javax.swing.JTable();
		jpanelrightdown = new javax.swing.JPanel();
		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		jDateFrom = new com.toedter.calendar.JDateChooser();
		jDateTo = new com.toedter.calendar.JDateChooser();
		jBtnThongKe = new javax.swing.JButton();
		revenueStatisBus = new ThongKeDoanhThuBUS();

		setBackground(new java.awt.Color(204, 204, 204));
		setLayout(new java.awt.GridLayout(1, 0));

		jpanelleft.setBackground(new java.awt.Color(255, 255, 255));
		jpanelleft.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

		jpanelhist.setBackground(new java.awt.Color(153, 255, 153));

		javax.swing.GroupLayout jpanelhistLayout = new javax.swing.GroupLayout(jpanelhist);
		jpanelhist.setLayout(jpanelhistLayout);
		jpanelhistLayout.setHorizontalGroup(jpanelhistLayout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 473, Short.MAX_VALUE));
		jpanelhistLayout.setVerticalGroup(jpanelhistLayout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 241, Short.MAX_VALUE));

		jpanelspline.setBackground(new java.awt.Color(0, 255, 255));

		javax.swing.GroupLayout jpanelsplineLayout = new javax.swing.GroupLayout(jpanelspline);
		jpanelspline.setLayout(jpanelsplineLayout);
		jpanelsplineLayout.setHorizontalGroup(jpanelsplineLayout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 473, Short.MAX_VALUE));
		jpanelsplineLayout.setVerticalGroup(jpanelsplineLayout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 241, Short.MAX_VALUE));

		javax.swing.GroupLayout jpanelleftLayout = new javax.swing.GroupLayout(jpanelleft);
		jpanelleft.setLayout(jpanelleftLayout);
		jpanelleftLayout.setHorizontalGroup(jpanelleftLayout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addComponent(jpanelhist, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
						Short.MAX_VALUE)
				.addComponent(jpanelspline, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
						Short.MAX_VALUE));
		jpanelleftLayout
				.setVerticalGroup(jpanelleftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(jpanelleftLayout.createSequentialGroup()
								.addComponent(jpanelspline, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(jpanelhist, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

		jpanelhist.setLayout(new BorderLayout());
		jpanelspline.setLayout(new BorderLayout());

		add(jpanelleft);

		jpanelright.setBackground(new java.awt.Color(255, 255, 255));
		jpanelright.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

		jpanelrightup.setBackground(new java.awt.Color(255, 255, 255));

		jLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
		jLabel.setText("Từ ngày");

		jTable1.setModel(new javax.swing.table.DefaultTableModel(new Object[][] { { null, null, null },
				{ null, null, null }, { null, null, null }, { null, null, null } },
				new String[] { "Mã hóa đơn", "Ngày tạo", "Tổng tiền" }));
		jScrollPane1.setViewportView(jTable1);

		javax.swing.GroupLayout jpanelrightupLayout = new javax.swing.GroupLayout(jpanelrightup);
		jpanelrightup.setLayout(jpanelrightupLayout);
		jpanelrightupLayout
				.setHorizontalGroup(jpanelrightupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(jpanelrightupLayout.createSequentialGroup().addContainerGap()
								.addGroup(jpanelrightupLayout
										.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addComponent(jScrollPane1).addGroup(jpanelrightupLayout.createSequentialGroup()
												.addComponent(jLabel).addGap(0, 0, Short.MAX_VALUE)))
								.addContainerGap()));
		jpanelrightupLayout
				.setVerticalGroup(jpanelrightupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(jpanelrightupLayout.createSequentialGroup().addGap(15, 15, 15).addComponent(jLabel)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
								.addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
								.addContainerGap()));

		jpanelrightdown.setBackground(new java.awt.Color(255, 255, 255));

		jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
		jLabel1.setText("Từ");

		jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
		jLabel2.setText("Đến");

		jBtnThongKe.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
		jBtnThongKe.setText("Thống kê");

		jBtnThongKe.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jBtnThongKeActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout jpanelrightdownLayout = new javax.swing.GroupLayout(jpanelrightdown);
		jpanelrightdown.setLayout(jpanelrightdownLayout);
		jpanelrightdownLayout.setHorizontalGroup(jpanelrightdownLayout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jpanelrightdownLayout.createSequentialGroup().addGap(15, 15, 15).addComponent(jLabel1)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(jDateFrom, javax.swing.GroupLayout.PREFERRED_SIZE, 146,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(jLabel2)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(jDateTo, javax.swing.GroupLayout.PREFERRED_SIZE, 146,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(jBtnThongKe, javax.swing.GroupLayout.DEFAULT_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addGap(10, 10, 10)));
		jpanelrightdownLayout.setVerticalGroup(jpanelrightdownLayout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jpanelrightdownLayout.createSequentialGroup()
						.addGroup(jpanelrightdownLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(jpanelrightdownLayout.createSequentialGroup().addGap(47, 47, 47)
										.addGroup(jpanelrightdownLayout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(jDateTo, javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(jDateFrom, javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(jLabel2).addComponent(jLabel1)))
								.addGroup(jpanelrightdownLayout.createSequentialGroup().addGap(35, 35, 35).addComponent(
										jBtnThongKe, javax.swing.GroupLayout.PREFERRED_SIZE, 48,
										javax.swing.GroupLayout.PREFERRED_SIZE)))
						.addContainerGap(157, Short.MAX_VALUE)));

		javax.swing.GroupLayout jpanelrightLayout = new javax.swing.GroupLayout(jpanelright);
		jpanelright.setLayout(jpanelrightLayout);
		jpanelrightLayout.setHorizontalGroup(jpanelrightLayout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addComponent(jpanelrightup, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
						Short.MAX_VALUE)
				.addComponent(jpanelrightdown, javax.swing.GroupLayout.Alignment.TRAILING,
						javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
		jpanelrightLayout
				.setVerticalGroup(jpanelrightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(jpanelrightLayout.createSequentialGroup()
								.addComponent(jpanelrightup, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(jpanelrightdown, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

		add(jpanelright);
	}// </editor-fold>//GEN-END:initComponents

    private void jBtnThongKeActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jBtnThongKeActionPerformed
        handleEvents();
    }// GEN-LAST:event_jBtnThongKeActionPerformed

    private void handleEvents() {
        if (jDateFrom.getDate().after(jDateTo.getDate())) {
            JOptionPane.showMessageDialog(null, "Ngày bắt đầu không thể lớn hơn ngày kết thúc");
            return;
        }

        LocalDateTime fromDate = getFromDate();
        LocalDateTime toDate = getToDate();

        setDateOnLabel(fromDate, toDate);
        renderSellInvoices(fromDate, toDate);
        createCharts(fromDate, toDate);
    }

    private void renderSellInvoices(LocalDateTime fromDate, LocalDateTime toDate) {
        DefaultTableModel tableModel = ((DefaultTableModel) jTable1.getModel());

        tableModel.setRowCount(0);

        ArrayList<HoaDonBan> sellInvoices = revenueStatisBus.getSellInvoices(fromDate, toDate);

        if (sellInvoices != null) {
            sellInvoices.forEach(invoice -> {
                tableModel.addRow(new Object[]{invoice.getMaHD(), invoice.getNgayTao().format(DateTimeFormatter.ofPattern("dd/MM/yyyy")), invoice.getTongTien()});
            });
        } else {
            JOptionPane.showMessageDialog(null, "Null");
        }
    }

    private void setDateOnLabel(LocalDateTime fromDate, LocalDateTime toDate) {
        jLabel.setText("Từ ngày: " + new SimpleDateFormat("dd/MM/yyyy").format(jDateFrom.getDate()) + "-" + new SimpleDateFormat("dd/MM/yyyy").format(jDateTo.getDate()));
    }

    private LocalDateTime getFromDate() {
        LocalDateTime fromDate = jDateFrom.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDateTime();
        jDateFrom.setDate(Date.from(fromDate.atZone(ZoneId.systemDefault()).toInstant()));
        return fromDate;
    }

    private LocalDateTime getToDate() {
        LocalDateTime toDate = jDateTo.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDateTime();
        jDateTo.setDate(Date.from(toDate.atZone(ZoneId.systemDefault()).toInstant()));
        return toDate;
    }

    private void createCharts(LocalDateTime fromTime, LocalDateTime toTime) {
        ArrayList<HoaDonBan> totalMonths = revenueStatisBus.getTotalMonths(fromTime, toTime);

        datasethist = new DefaultCategoryDataset();

        // Add sales
        if (totalMonths.size() == 0) {
            datasethist.addValue(0, "Doanh thu", "");
        } else {
            totalMonths.forEach(total -> {
                String formattedDate = total.getNgayTao().format(DateTimeFormatter.ofPattern("dd/MM/yyyy"));
                datasethist.addValue(total.getTongTienThang(), "Doanh thu", formattedDate);
            });
        }

        // bar chart
        JFreeChart barChart = ChartFactory.createBarChart("", "Ngày", "Doanh thu", datasethist);

        // create a plot
        CategoryPlot categoryBarPlot = barChart.getCategoryPlot();
        categoryBarPlot.setBackgroundPaint(new Color(255, 250, 205));

        // create vertical bars
        BarRenderer bar = (BarRenderer) categoryBarPlot.getRenderer();
        bar.setSeriesPaint(0, new Color(135, 206, 250));

        // create bar chart panel
        ChartPanel barChartPanel = new ChartPanel(barChart);
        jpanelhist.removeAll();
        jpanelhist.add(barChartPanel);
        jpanelhist.revalidate();
        jpanelhist.repaint();

        // LINE
        // line chart
        JFreeChart lineChart = ChartFactory.createLineChart("", "Ngày", "Doanh Thu", datasethist, PlotOrientation.VERTICAL, true, true, false);

        // create a plot
        CategoryPlot categoryLinePlot = lineChart.getCategoryPlot();
        LineAndShapeRenderer line = new LineAndShapeRenderer(true, true);
        categoryLinePlot.setRenderer(line);

        // create x axis (Ngày)
        CategoryAxis xAxis = (CategoryAxis) categoryLinePlot.getDomainAxis();
        xAxis.setCategoryLabelPositions(CategoryLabelPositions.STANDARD);

        // create y axis (Doanh thu)
        NumberAxis yAxis = (NumberAxis) categoryLinePlot.getRangeAxis();
        yAxis.setAutoRangeIncludesZero(false);

        ChartPanel lineChartPanel = new ChartPanel(lineChart);
        jpanelspline.removeAll();
        jpanelspline.add(lineChartPanel);
        jpanelspline.revalidate();
        jpanelspline.repaint();
    }

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton jBtnThongKe;
	private com.toedter.calendar.JDateChooser jDateFrom;
	private com.toedter.calendar.JDateChooser jDateTo;
	private javax.swing.JLabel jLabel;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JTable jTable1;
	private javax.swing.JPanel jpanelhist;
	private javax.swing.JPanel jpanelleft;
	private javax.swing.JPanel jpanelright;
	private javax.swing.JPanel jpanelrightdown;
	private javax.swing.JPanel jpanelrightup;
	private javax.swing.JPanel jpanelspline;
	// End of variables declaration//GEN-END:variables
	private JFreeChart charthist;
    private JFreeChart chartspline;
    private DefaultCategoryDataset datasethist; // used for bar chart
    private XYDataset datasetspline; // used for line chart

}
